version = 0.1
[default.deploy.parameters]
stack_name = "fcj-book-shop"
resolve_s3 = true
s3_prefix = "fcj-book-shop"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BookShopWebName=\"fcj-book-shop\" S3ImageShopName=\"book-image-shop\" S3ImageResizedName=\"book-image-resize-shop\""
image_repositories = []
disable_rollback = true
