version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fcj-book-shop"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13ys1igyj92vs"
s3_prefix = "fcj-book-shop"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
